default/urls.py
from django.conf.urls import url

from . import views

app_name = 'default'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^home$', views.home, name="home"),
    url(r'^register$', views.register, name="register"),
    url(r'^profile$', views.profile, name="profile"),
    url(r'^profile/update$', views.profile_update, name="profile_update"),
    url(r'^(?P<user_id>[0-9]+)/thanks$', views.thanks, name="thanks"),
    url(r'^author/conferences$', views.author_conferences, name="author_conferences"),
    url(r'^author/submissions$', views.author_submissions, name="author_submissions"),
    url(r'^papers/$', views.papers, name="papers"),
    url(r'^author/submissions/(?P<conf_id>[0-9]+)/upload$', views.author_submissions_upload, name="author_submissions_upload"),
    url(r'^author/submission/info/(?P<submission_id>[0-9]+)$', views.author_submissions_info, name="author_submissions_info"),
    url(r'^support$', views.support_index, name="support_index"),
    url(r'^news$', views.news_index, name="news_index"),
    url(r'^author/reviews$', views.author_reviews, name="author_reviews"),
    url(r'^conference/search$', views.conference_search, name="conference_search"),
    url(r'^conference/register$', views.conference_register, name="conference_register"),
    url(r'^conference/info/(?P<conf_id>[0-9]+)$', views.conference_info, name="conference_info"),
    url(r'^conference/thanks/(?P<conf_id>[0-9]+)$', views.conference_thanks, name="conference_thanks")
]

easychair/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    	url(r'^admin/', admin.site.urls),
        url(r'^polls/', include('polls.urls')),
        url(r'^default/', include('default.urls')),
]


from django.views.generic import RedirectView
urlpatterns += [
     url(r'^$', RedirectView.as_view(url='/default/home')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote')
]

default/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    type = models.CharField(max_length=100, default="admin", blank=False, null=False)
    location = models.CharField(max_length=100, blank=True, null=True)
    skype = models.CharField(max_length=100, blank=True, null=True)
    facebook = models.CharField(max_length=100, blank=True, null=True)
    twitter = models.CharField(max_length=100, blank=True, null=True)
    interests = models.TextField(blank=True, null=True)
    photoURL =  models.CharField(max_length=250, blank=False, null=False)
    REQUIRED_FIELDS = ['type', 'email', 'first_name', 'last_name']


from .managers import AdminUserManager
class AdminUser(User):
    objects = AdminUserManager()

    class Meta:
        proxy = True
        ordering = ('first_name', )

    def do_something(self):
        pass

from .managers import ReviewerUserManager
class ReviewerUser(User):
    objects = ReviewerUserManager()

    class Meta:
        proxy = True
        ordering = ('first_name', )

    def do_something(self):
        pass

from .managers import AuthorUserManager
class AuthorUser(User):
    objects = AuthorUserManager()

    class Meta:
        proxy = True
        ordering = ('first_name', )

    def do_something(self):
        pass

class Conference(models.Model):
    id = models.AutoField(primary_key=True, help_text="conference id")
    name = models.CharField(max_length=20,  help_text="name of conference", unique=True)
    users = models.ManyToManyField(User)
    acronym = models.CharField(max_length=20,  help_text="acronym", unique=True)
    webpage = models.CharField(max_length=20,  help_text="web page", unique=True)
    city = models.CharField(max_length=200, help_text="Enter a city")
    country_id = models.IntegerField( help_text="country")
    start_date = models.DateTimeField(auto_now=False)
    end_date = models.DateTimeField(auto_now=False)
    contact_email = models.CharField(max_length=200, help_text="contact_emai")
    webpage = models.CharField(max_length=200, help_text="webpage")
    banner = models.CharField(max_length=200, help_text="banner")
    license_expiry = models.CharField(max_length=200, help_text="status")
    status = models.BooleanField(max_length=200, help_text="status")

    def __unicode__(self):
         return self.acronym

class Submission(models.Model):
    id = models.AutoField(primary_key=True, help_text="reviewer")
    conference = models.ForeignKey('Conference',on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200, help_text="Enter a title")
    abstract = models.TextField( help_text="Enter a abstract")
    keywords = models.CharField(max_length=200, help_text="keywords")
    paper_url = models.CharField(max_length=200, help_text="paper url")
    status = models.CharField(max_length=200, help_text="status")

class Country(models.Model):
    id = models.AutoField(primary_key=True, help_text="reviewer")
    code = models.CharField(max_length=2,  help_text="country code", null=True)
    country = models.CharField(max_length=200,  help_text="name of conference")

    def __unicode__(self):
         return self.country

class Correspondence(models.Model):
    id = models.AutoField(primary_key=True, help_text="reviewer")
    submission = models.ForeignKey('Submission',on_delete=models.SET_NULL, null=True)
    address1 = models.CharField(max_length=200,  help_text="name of conference")
    address2 = models.CharField(max_length=200,  help_text="name of conference")
    city = models.CharField(max_length=200,  help_text="name of conference")
    state = models.CharField(max_length=200,  help_text="name of conference")
    country = models.ForeignKey('Country',on_delete=models.SET_NULL, null=True)

class Author(models.Model):
    id = models.AutoField(primary_key=True, help_text="reviewer")
    submission = models.ForeignKey('Submission',on_delete=models.SET_NULL, null=True)
    fname = models.CharField(max_length=100,  help_text="name of conference")
    lname = models.CharField(max_length=100,  help_text="name of conference")
    email = models.CharField(max_length=200,  help_text="name of conference")
    organisation = models.CharField(max_length=200,  help_text="name of conference", null=True)
    speaker = models.NullBooleanField(max_length=200,  help_text="speaker", default=True)

default/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

from django.http import HttpResponseRedirect

from django.urls import reverse

from django.conf import settings

from django.contrib.auth.decorators import login_required
# Create your views here.

from django.contrib.auth.decorators import user_passes_test


def home(request):
    return render(request, 'default/home.html')

@login_required(login_url='/accounts/login/')
def index(request):
    # if not request.user.is_authenticated:
    #     return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    user = request.user

    if user.type == 'author':
        output = "welcome author"
        conference_count = user.conference_set.count()
        submission_count = user.submission_set.count()
        review_count = user.submission_set.count()


        submissions = user.submission_set.all().order_by('-id')[:5]
        conferences = user.conference_set.all().order_by('-id')[:5]

        context = {
            'output': output,
            'conference_count' : conference_count,
            'submission_count' : submission_count,
            'review_count' : review_count,
            'submissions' : submissions,
            'conferences' : conferences
        }
        return render(request, 'default/index.html', {'con' : context})

    elif user.type == 'reviewer':
        output = "welcome reviewer"
        context = {'output': output}
        return render(request, 'default/index.html', context)
    elif user.type == 'chair':
        output = "welcome chair"
        context = {'output': output}
        return render(request, 'default/index.html', context)

@login_required(login_url='/accounts/login/')
def profile(request):
    # if not request.user.is_authenticated:
    #     return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    return render(request, 'default/profile.html', {})


from django.core.files.storage import FileSystemStorage

@login_required(login_url="/accounts/login")
def profile_update( request ):
    # if this is a POST request we need to process the form
    if request.method == 'POST':

        user = request.user

        user.first_name = request.POST['first_name']

        user.last_name = request.POST['last_name']

        user.email = request.POST['email']

        user.location = request.POST['location']

        user.skype = request.POST['skype']

        user.twitter = request.POST['twitter']

        user.facebook = request.POST['facebook']

        user.interests = request.POST['interests']

        if 'picture' in request.FILES.keys() and request.FILES['picture']:

            picture = request.FILES['picture']

            fs = FileSystemStorage()

            filename = fs.save(picture.name, picture)

            uploaded_file_url = fs.url(filename)

            user.photoURL = uploaded_file_url;

        user.save()

    return HttpResponseRedirect(reverse( "default:profile"))


from .forms import RegisterForm

from default.models import AdminUser, User, AuthorUser

from django.contrib.auth.hashers import PBKDF2PasswordHasher

from django.contrib.auth import authenticate, login

def register(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        #print form
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            cleaned_data = form.cleaned_data

            print "cleaned_data", cleaned_data

            hasher = PBKDF2PasswordHasher()

            password = hasher.encode(password=cleaned_data['password'], salt='salt', iterations=36000)

            user = AuthorUser(id=None,
                                first_name=cleaned_data['fname'],
                                last_name=cleaned_data['lname'],
                                username=cleaned_data['email'],
                                password=password,
                                email=cleaned_data['email'],
                                is_staff=True,
                                type="author"
                            )
            user.save()

            login_user = authenticate(username=user.username, password=cleaned_data['password'])

            print( "login_user is ", login_user )

            if login_user is not None:

                login(request, login_user)
                # redirect to a new URL:
                #return HttpResponseRedirect('/thanks/')
                #return HttpResponseRedirect(reverse( "default:thanks", args=(question.id, )))
                return HttpResponseRedirect(reverse( "default:thanks", args=(login_user.id, )))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegisterForm()

    return render( request, 'default/register.html', {'form': form} )

def thanks( request, user_id ):

    user = User.objects.get(pk=user_id)

    context = {'user': user}

    return render( request, 'default/thanks.html', context )


def papers( request ):

    user = request.user.id

    context = {'user': user}

    return render( request, 'default/papers.html', context )

from .forms import CorrespondenceForm, AuthorForm, PaperForm


from default.models import AuthorUser, User, Conference, Submission

@login_required(login_url='/accounts/login/')
def author_conferences( request ):
    user = request.user
    conferences = user.conference_set.all()
    print conferences.count()

    #onferences = user.conference_set.all()
    return render( request, 'default/authors/conferences.html', {'conferences' : conferences})

def author_submissions( request ):
    user = request.user
    submissions = user.submission_set.all()
    print submissions.count()

    #onferences = user.conference_set.all()
    return render( request, 'default/authors/submissions.html', {'submissions' : submissions})

from .models import Correspondence, Author, Country
from django.http import HttpResponse
from .utils import get_post_dict
from django.shortcuts import get_object_or_404


@login_required(login_url='/accounts/login/')
def author_submissions_upload( request, conf_id ):
    conference = get_object_or_404(Conference, pk = conf_id)
    user = request.user
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CorrespondenceForm(request.POST)
        form3 = PaperForm(request.POST,request.FILES)
        title = request.POST.getlist('title', [])
        fname = request.POST.getlist('fname', [])
        lname = request.POST.getlist('lname', [])
        email = request.POST.getlist('email', [])
        organisation = request.POST.getlist('organisation', [])
        speaker = request.POST.getlist('speaker', [])

        authors = []
        author = {}

        length = len(title)
        for i in range(0, length):
            author['title'] = title[i]
            author['fname'] = fname[i]
            author['lname'] = lname[i]
            author['email'] = email[i]
            author['organisation'] = organisation[i]
            if 0 <= i < len(speaker):
                author['speaker'] = speaker[i]
            form2 = AuthorForm( author )
            if form2.is_valid():
                authors.append( author )


        #print form
        # check whether it's valid:

        if form.is_valid() and form3.is_valid():
            cleaned_data = form3.cleaned_data

            upload = cleaned_data['upload']

            fs = FileSystemStorage()

            filename = fs.save(upload.name, upload)

            paper_url = fs.url(filename)

            submission = Submission.objects.create(
                conference = conference,
                user = user,
                title= cleaned_data['paper_title'] ,
                abstract= cleaned_data['abstract'] ,
                keywords = cleaned_data['keywords'],
                paper_url = paper_url,
                status = "pending"
            )
            submission.save()

            cleaned_data = form.cleaned_data
            country = cleaned_data['country']

            correspondence = Correspondence.objects.create(
                submission = submission,
                address1 = cleaned_data['address1'],
                address2 = cleaned_data['address2'],
                city = cleaned_data['city'],
                state = cleaned_data['state'],
                country = country
            )
            correspondence.save()

            for a in authors:
                author = Author.objects.create(
                    submission = submission,
                    fname = a['fname'],
                    lname = a['lname'],
                    email = a['email'],
                    organisation = a['organisation'],
                    speaker = a['speaker']
                )
                author.save()
            return HttpResponseRedirect(reverse('default:author_submissions_info', kwargs={'submission_id':submission.id}))

    else:
        form = CorrespondenceForm()
        form2 = AuthorForm()
        form3 = PaperForm()

    return render( request, 'default/authors/submission_upload.html', {'conference':conference, 'form': form, 'form2' : form2, 'form3' : form3} )

@login_required(login_url='/accounts/login/')
def author_submissions_info( request, submission_id ):

    submission = get_object_or_404( Submission, pk = submission_id )

    conference = submission.conference

    authors = submission.author_set.all()

    print authors

    correspondence = submission.correspondence_set.all()

    return render( request, 'default/submission_info.html', {'conference':conference, 'submission': submission, 'authors' : authors} )


@login_required(login_url='/accounts/login/')
def support_index(request):

default/templates/default/authors/conferences.html
{% extends "default/index2.html" %}
{% load static %}
{% block content %}
<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <ol class="breadcrumb pull-right">
                            <li><a href="#">{{ user.type }}</a></li>
                            <li class="active">Dashboard</li>
                        </ol>
                        <h4 class="page-title">Welcome ! {{ user.first_name }}</h4>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-12">
                    <div class="card-box">
                        <h4 class="text-dark  header-title m-t-0">Conferences</h4>
                        <p class="text-muted m-b-25 font-13">
                            You have registered in the following conferences
                        </p>

                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Conference</th>
                                    <th>Location</th>
                                    <th>Dates</th>
                                    <th>View Website</th>
                                    <th>Contact Person</th>
                                    <th>Submission</th>
                                </tr>
                                </thead>
                                <tbody>
                                  {% for conference in conferences %}
                                    <tr>
                                        <td>{{ conference.id }}</td>
                                        <td><a href="{% url 'default:conference_info' conf_id=conference.id %}">{{ conference.name }}</a></td>
                                        <td>{{ conference.city }}</td>
                                        <td>{{ conference.start_date }}</td>
                                        <td><span class="label label-info">{{ conference.webpage }}</span></td>
                                        <td>{{ conference.contact_email }}</td>
                                        <td>{{ conference.submission_set.count }}</td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- end col -8 -->
            </div>
            <!-- end row -->


        </div>
        <!-- end container -->
    </div>
    <!-- end content -->
{% endblock %}

default/templates/default/authors/submissions.html
{% extends "default/index2.html" %}
{% load static %}
{% block content %}
<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <ol class="breadcrumb pull-right">
                            <li><a href="#">{{ user.type }}</a></li>
                            <li class="active">Dashboard</li>
                        </ol>
                        <h4 class="page-title">Welcome ! {{ user.first_name }}</h4>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-12">
                    <div class="card-box">
                        <h4 class="text-dark  header-title m-t-0">Submissions</h4>
                        <p class="text-muted m-b-25 font-13">
                            You have the following uploaded submissions.
                        </p>

                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Conference</th>
                                    <th>Title</th>
                                    <th>Authors</th>
                                    <th>Status</th>
                                    <th>More Information</th>
                                </tr>
                                </thead>
                                <tbody>
                                  {% for submission in submissions %}
                                    <tr>
                                        <td>{{ submission.id }}</td>
                                        <td>
                                          <a href="{% url 'default:conference_info' conf_id=submission.conference.id %}">
                                          {{ submission.conference.name }}
                                          </a>
                                        </td>
                                        <td>{{ submission.title }}</td>
                                        <td>
                                          {% for author in submission.author_set.all %}
                                            {{ author.fname }} {{ author.lname }} <br />
                                          {% endfor %}
                                        </td>
                                        <!-- <td><a href="{{ submission.paper_url }}">Download</a></td> -->
                                        <td><span class="label label-info">{{ submission.status }}</span></td>
                                        <td><a href="{% url 'default:author_submissions_info' submission_id=submission.id %}">more info</a></td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- end col -8 -->
            </div>
            <!-- end row -->


        </div>
        <!-- end container -->
    </div>
    <!-- end content -->
{% endblock %}